import Link from "next/link";
import { SectionHeading } from "@/components/ui/section-heading";
import {
  HiOutlineArrowRight,
  HiOutlineUserPlus,
  HiOutlineLink,
  HiOutlineBanknotes,
  HiOutlineChartBarSquare,
  HiOutlineCheckCircle,
} from "react-icons/hi2";

const steps = [
  {
    icon: HiOutlineUserPlus,
    title: "Create Your Account",
    description:
      "Sign up for a KulmiPay account and complete verification. You'll get access to your unique referral dashboard immediately.",
  },
  {
    icon: HiOutlineLink,
    title: "Share Your Link",
    description:
      "Copy your unique referral link and share it — via email, social media, WhatsApp, or word-of-mouth. Every sign-up is tracked automatically.",
  },
  {
    icon: HiOutlineBanknotes,
    title: "Earn Commissions",
    description:
      "Earn a 1.2% commission on the revenue generated by your referrals every time they transact. Commissions are paid out quarterly.",
  },
];

const highlights = [
  {
    icon: HiOutlineChartBarSquare,
    title: "Real-Time Tracking",
    description:
      "Monitor your referral performance, click-through rates, and earnings from your KulmiPay dashboard in real-time.",
  },
  {
    icon: HiOutlineBanknotes,
    title: "Uncapped Earnings",
    description:
      "There's no limit to how many people you can refer. The more businesses you bring to KulmiPay, the more you earn.",
  },
  {
    icon: HiOutlineCheckCircle,
    title: "Quarterly Payouts",
    description:
      "Commissions are calculated monthly and credited to your account every three months, as long as your referrals remain active.",
  },
];

export function ReferralsContent() {
  return (
    <>
      {/* Hero */}
      <section className='relative overflow-hidden'>
        <div className='absolute inset-0 bg-linear-to-br from-brand-50 via-white to-brand-100 dark:from-[#0A0A0B] dark:via-[#0F0D0B] dark:to-[#1A1510]' />
        <div className='absolute top-20 -right-40 w-150 h-150 rounded-full bg-brand/8 blur-[120px] pointer-events-none' />
        <div className='relative w-full px-6 md:px-12 pt-32 pb-6 md:pt-40 md:pb-8'>
          <div className='max-w-3xl'>
            <h1 className='text-3xl md:text-6xl font-bold tracking-tight leading-[1.1] mb-4'>
              Earn by{" "}
              <span className='bg-linear-to-r from-brand via-brand-dark to-brand bg-clip-text text-transparent'>
                Referring
              </span>
              <br />
              Businesses to KulmiPay
            </h1>
            <p className='text-sm md:text-lg text-muted-foreground max-w-2xl leading-relaxed'>
              Share KulmiPay with your network and earn 1.2% commission on every
              transaction your referrals make. No cap on earnings, no limits on
              referrals.
            </p>
            <div className='mt-8'>
              <Link
                href='https://app.kulmipay.com/account/signup/'
                className='group inline-flex items-center gap-2 px-8 py-4 text-base font-semibold text-white bg-brand rounded-xl hover:bg-brand-dark transition-all shadow-lg hover:-translate-y-0.5'>
                Start Earning Today
                <HiOutlineArrowRight
                  size={18}
                  className='group-hover:translate-x-0.5 transition-transform'
                />
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className='py-6 md:py-10'>
        <div className='w-full px-6 md:px-12'>
          <div className='text-center mb-6 md:mb-10'>
            <h2 className='text-2xl md:text-4xl font-bold tracking-tight'>
              How It Works
            </h2>
          </div>
          <div className='grid md:grid-cols-3 gap-8 max-w-5xl mx-auto'>
            {steps.map((step, idx) => (
              <div
                key={step.title}
                className='relative flex flex-col items-center text-center group'>
                {idx < steps.length - 1 && (
                  <div className='hidden md:block absolute top-10 left-[calc(50%+3rem)] w-[calc(100%-6rem)] h-0.5 bg-linear-to-r from-brand/30 to-brand/5' />
                )}
                <div className='relative mb-6'>
                  <div className='w-20 h-20 rounded-2xl bg-white dark:bg-white/5 border-2 border-brand/20 flex items-center justify-center shadow-lg group-hover:border-brand/50 transition-all'>
                    <step.icon size={32} className='text-brand' />
                  </div>
                  <span className='absolute -top-2 -right-2 w-7 h-7 bg-brand text-white text-xs font-bold rounded-full flex items-center justify-center shadow-md'>
                    {idx + 1}
                  </span>
                </div>
                <h3 className='text-lg font-semibold mb-2'>{step.title}</h3>
                <p className='text-sm text-muted-foreground leading-relaxed max-w-xs'>
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Earning Details */}
      <section className='py-6 md:py-10 bg-gray-50/80 dark:bg-[#0A0A0B] relative overflow-hidden'>
        <div className='absolute top-0 right-0 w-125 h-125 rounded-full bg-brand/5 blur-[120px] pointer-events-none' />
        <div className='relative w-full px-6 md:px-12'>
          <div className='grid md:grid-cols-2 gap-10 md:gap-16 items-center'>
            <div>
              <SectionHeading
                title='Earn Per Transaction'
                subtitle="Every time a business you referred processes a payment through KulmiPay, you earn 1.2% of the revenue generated. There's no cap — grow your network and watch your earnings compound."
              />
              <div className='space-y-4'>
                {highlights.map((h) => (
                  <div key={h.title} className='flex items-start gap-4'>
                    <div className='p-2 rounded-lg bg-brand/10 text-brand shrink-0 mt-0.5'>
                      <h.icon size={20} />
                    </div>
                    <div>
                      <h4 className='font-semibold text-foreground text-sm'>
                        {h.title}
                      </h4>
                      <p className='text-sm text-muted-foreground leading-relaxed'>
                        {h.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className='rounded-2xl border bg-muted/30 dark:bg-white/3 border-border dark:border-white/8 p-8 text-center'>
              <div className='text-6xl font-bold text-brand mb-2'>1.2%</div>
              <p className='text-muted-foreground text-sm mb-6'>
                Commission per transaction
              </p>
              <div className='h-px bg-border mb-6' />
              <div className='text-3xl font-bold text-foreground mb-2'>
                $0 — ∞
              </div>
              <p className='text-muted-foreground text-sm'>
                No cap on your earnings
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className='relative py-6 md:py-10 overflow-hidden'>
        <div className='absolute inset-0 bg-white dark:bg-[#0A0A0B]' />
        <div className='relative w-full px-6 md:px-12 text-center'>
          <h2 className='text-2xl md:text-4xl font-bold text-foreground mb-6'>
            Start Earning
          </h2>
          <p className='text-lg text-muted-foreground max-w-2xl mx-auto mb-10'>
            Create your free KulmiPay account, grab your referral link, and
            start earning commissions today.
          </p>
          <Link
            href='https://app.kulmipay.com/account/signup/'
            className='group inline-flex items-center gap-2 px-8 py-4 text-base font-semibold text-white bg-brand rounded-xl hover:bg-brand-dark transition-all shadow-lg hover:-translate-y-0.5'>
            Get Your Referral Link
            <HiOutlineArrowRight
              size={18}
              className='group-hover:translate-x-0.5 transition-transform'
            />
          </Link>
        </div>
      </section>
    </>
  );
}
